# Generated by Django 3.2 on 2022-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
